// Generated by CIRCT firtool-1.128.0
`ifndef layers_XcoreTop_Verification_Assert
  `define layers_XcoreTop_Verification_Assert
  `include "layers-XcoreTop-Verification.sv"
`endif // not def layers_XcoreTop_Verification_Assert
