// Generated by CIRCT firtool-1.128.0
`ifndef layers_ifuTop_Verification_Assert
  `define layers_ifuTop_Verification_Assert
  `include "layers-ifuTop-Verification.sv"
`endif // not def layers_ifuTop_Verification_Assert
