// Generated by CIRCT firtool-1.128.0
module BasicFifo(
  input         clock,
  input         reset,
  input         io_push,
  input         io_pop,
  input  [31:0] io_din,
  output [31:0] io_dout
);

  wire        io_push_0 = io_push;
  wire        io_pop_0 = io_pop;
  wire [31:0] io_din_0 = io_din;
  reg  [31:0] entryArray_0;
  reg  [31:0] entryArray_1;
  reg  [31:0] entryArray_2;
  reg  [31:0] entryArray_3;
  reg  [31:0] entryArray_4;
  reg  [31:0] entryArray_5;
  reg  [31:0] entryArray_6;
  reg  [31:0] entryArray_7;
  reg  [2:0]  writePtr_Q;
  reg  [2:0]  readPtr_Q;
  wire [7:0]  readPtrDcd = 8'h1 << readPtr_Q;
  wire [7:0]  writePtrDcd = 8'h1 << writePtr_Q;
  wire [3:0]  _GEN = 4'({1'h0, readPtr_Q} + 4'h1);
  wire        writePtrDcdWv_0 = writePtrDcd[0] & io_push_0;
  wire        writePtrDcdWv_1 = writePtrDcd[1] & io_push_0;
  wire        writePtrDcdWv_2 = writePtrDcd[2] & io_push_0;
  wire        writePtrDcdWv_3 = writePtrDcd[3] & io_push_0;
  wire        writePtrDcdWv_4 = writePtrDcd[4] & io_push_0;
  wire        writePtrDcdWv_5 = writePtrDcd[5] & io_push_0;
  wire        writePtrDcdWv_6 = writePtrDcd[6] & io_push_0;
  wire        writePtrDcdWv_7 = writePtrDcd[7] & io_push_0;
  wire [3:0]  _GEN_0 = 4'({1'h0, writePtr_Q} + 4'h1);
  wire [31:0] io_dout_0 =
    (readPtrDcd[0] ? entryArray_0 : 32'h0) | (readPtrDcd[1] ? entryArray_1 : 32'h0)
    | (readPtrDcd[2] ? entryArray_2 : 32'h0) | (readPtrDcd[3] ? entryArray_3 : 32'h0)
    | (readPtrDcd[4] ? entryArray_4 : 32'h0) | (readPtrDcd[5] ? entryArray_5 : 32'h0)
    | (readPtrDcd[6] ? entryArray_6 : 32'h0) | (readPtrDcd[7] ? entryArray_7 : 32'h0);
  always @(posedge clock) begin
    if (writePtrDcdWv_0)
      entryArray_0 <= io_din_0;
    else begin
    end
  end // always @(posedge)
  always @(posedge clock) begin
    if (writePtrDcdWv_1)
      entryArray_1 <= io_din_0;
    else begin
    end
  end // always @(posedge)
  always @(posedge clock) begin
    if (writePtrDcdWv_2)
      entryArray_2 <= io_din_0;
    else begin
    end
  end // always @(posedge)
  always @(posedge clock) begin
    if (writePtrDcdWv_3)
      entryArray_3 <= io_din_0;
    else begin
    end
  end // always @(posedge)
  always @(posedge clock) begin
    if (writePtrDcdWv_4)
      entryArray_4 <= io_din_0;
    else begin
    end
  end // always @(posedge)
  always @(posedge clock) begin
    if (writePtrDcdWv_5)
      entryArray_5 <= io_din_0;
    else begin
    end
  end // always @(posedge)
  always @(posedge clock) begin
    if (writePtrDcdWv_6)
      entryArray_6 <= io_din_0;
    else begin
    end
  end // always @(posedge)
  always @(posedge clock) begin
    if (writePtrDcdWv_7)
      entryArray_7 <= io_din_0;
    else begin
    end
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      writePtr_Q <= 3'h0;
    else if (io_push_0)
      writePtr_Q <= _GEN_0[2:0];
    else begin
    end
  end // always @(posedge, posedge)
  always @(posedge clock or posedge reset) begin
    if (reset)
      readPtr_Q <= 3'h0;
    else if (io_pop_0)
      readPtr_Q <= _GEN[2:0];
    else begin
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset) begin
        writePtr_Q = 3'h0;
        readPtr_Q = 3'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_dout = io_dout_0;
endmodule

