// Generated by CIRCT firtool-1.128.0
module Decoder(
  input         clock,
  input         reset,
  input  [31:0] io_inst,
  output [4:0]  io_uop_lsrc1,
  output [4:0]  io_uop_lsrc2,
  output [4:0]  io_uop_ldst
);

  wire [31:0] io_inst_0 = io_inst;
  wire [31:0] instInfoPla_io_inst = io_inst_0;
  wire [4:0]  io_uop_lsrc1_0 = io_inst_0[19:15];
  wire [4:0]  io_uop_lsrc2_0 = io_inst_0[24:20];
  wire [4:0]  io_uop_ldst_0 = io_inst_0[11:7];
  wire        instInfoPla_io_instDcd_src1Ren;
  wire        instInfoPla_io_instDcd_src2Ren;
  wire        instInfoPla_io_instDcd_dstWen;
  InstInfoPla instInfoPla (
    .clock              (clock),
    .reset              (reset),
    .io_inst            (instInfoPla_io_inst),
    .io_instDcd_src1Ren (instInfoPla_io_instDcd_src1Ren),
    .io_instDcd_src2Ren (instInfoPla_io_instDcd_src2Ren),
    .io_instDcd_dstWen  (instInfoPla_io_instDcd_dstWen)
  );
  wire        instDcd_src1Ren = instInfoPla_io_instDcd_src1Ren;
  wire        instDcd_src2Ren = instInfoPla_io_instDcd_src2Ren;
  wire        instDcd_dstWen = instInfoPla_io_instDcd_dstWen;
  assign io_uop_lsrc1 = io_uop_lsrc1_0;
  assign io_uop_lsrc2 = io_uop_lsrc2_0;
  assign io_uop_ldst = io_uop_ldst_0;
endmodule

