// Generated by CIRCT firtool-1.128.0
module IfuTop(
  input          clock,
  input          reset,
  output         io_ifuARChannel_arValid,
  input          io_ifuARChannel_arReady,
  output [31:0]  io_ifuARChannel_arAddr,
  input          io_ifuRChannel_rValid,
  output         io_ifuRChannel_rReady,
  input  [127:0] io_ifuRChannel_rData,
  output         io_instValidVec_0,
  output [31:0]  io_instVec_0
);

  wire         instQueue_io_enqueueAllowIn;
  wire [31:0]  fetchInstVec_0;
  wire         io_ifuARChannel_arReady_0 = io_ifuARChannel_arReady;
  wire         io_ifuRChannel_rValid_0 = io_ifuRChannel_rValid;
  wire [127:0] io_ifuRChannel_rData_0 = io_ifuRChannel_rData;
  wire         io_ifuARChannel_arValid_0 = 1'h1;
  wire         io_ifuRChannel_rReady_0 = 1'h1;
  wire         instQueue_io_fetchValidVec_0 = 1'h1;
  wire         io_instValidVec_0_0 = io_ifuRChannel_rValid_0;
  reg  [63:0]  pc_Q;
  wire [31:0]  instQueue_io_fetchInstVec_0 = fetchInstVec_0;
  wire [31:0]  io_ifuARChannel_arAddr_0 = pc_Q[31:0];
  wire [31:0]  io_instVec_0_0 = io_ifuRChannel_rData_0[31:0];
  assign fetchInstVec_0 = io_ifuRChannel_rData_0[31:0];
  wire [64:0]  _GEN = 65'({1'h0, pc_Q} + 65'h4);
  wire [63:0]  pc_In = _GEN[63:0];
  wire         pc_wen = io_ifuARChannel_arValid_0 & io_ifuARChannel_arReady_0;
  InstQueue instQueue (
    .clock              (clock),
    .reset              (reset),
    .io_fetchValidVec_0 (instQueue_io_fetchValidVec_0),
    .io_enqueueAllowIn  (instQueue_io_enqueueAllowIn),
    .io_fetchInstVec_0  (instQueue_io_fetchInstVec_0)
  );
  always @(posedge clock or posedge reset) begin
    if (reset)
      pc_Q <= 64'h0;
    else if (pc_wen)
      pc_Q <= pc_In;
    else begin
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset)
        pc_Q = 64'h0;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_ifuARChannel_arValid = io_ifuARChannel_arValid_0;
  assign io_ifuARChannel_arAddr = io_ifuARChannel_arAddr_0;
  assign io_ifuRChannel_rReady = io_ifuRChannel_rReady_0;
  assign io_instValidVec_0 = io_instValidVec_0_0;
  assign io_instVec_0 = io_instVec_0_0;
endmodule

