// Generated by CIRCT firtool-1.128.0
module InstQueue(
  input        clock,
  input        reset,
  input        io_fetchValidVec_0,
  input        io_fetchValidVec_1,
  input        io_fetchValidVec_2,
  input        io_fetchValidVec_3,
  input [31:0] io_fetchInstVec_0,
  input [31:0] io_fetchInstVec_1,
  input [31:0] io_fetchInstVec_2,
  input [31:0] io_fetchInstVec_3
);

  wire [3:0]  fetchValidVecShifter_io_out;
  wire [31:0] InstFifoVec_3_io_inst_Q;
  wire [31:0] InstFifoVec_2_io_inst_Q;
  wire [31:0] InstFifoVec_1_io_inst_Q;
  wire [31:0] InstFifoVec_0_io_inst_Q;
  wire        io_fetchValidVec_0_0 = io_fetchValidVec_0;
  wire        io_fetchValidVec_1_0 = io_fetchValidVec_1;
  wire        io_fetchValidVec_2_0 = io_fetchValidVec_2;
  wire        io_fetchValidVec_3_0 = io_fetchValidVec_3;
  wire [31:0] io_fetchInstVec_0_0 = io_fetchInstVec_0;
  wire [31:0] io_fetchInstVec_1_0 = io_fetchInstVec_1;
  wire [31:0] io_fetchInstVec_2_0 = io_fetchInstVec_2;
  wire [31:0] io_fetchInstVec_3_0 = io_fetchInstVec_3;
  wire [31:0] InstFifoVec_0_io_inst_In = io_fetchInstVec_0_0;
  wire [31:0] InstFifoVec_1_io_inst_In = io_fetchInstVec_0_0;
  wire [31:0] InstFifoVec_2_io_inst_In = io_fetchInstVec_0_0;
  wire [31:0] InstFifoVec_3_io_inst_In = io_fetchInstVec_0_0;
  wire        InstFifoVec_0_io_push;
  InstFifo InstFifoVec_0 (
    .clock      (clock),
    .reset      (reset),
    .io_push    (InstFifoVec_0_io_push),
    .io_inst_In (InstFifoVec_0_io_inst_In),
    .io_inst_Q  (InstFifoVec_0_io_inst_Q)
  );
  wire        InstFifoVec_1_io_push;
  InstFifo InstFifoVec_1 (
    .clock      (clock),
    .reset      (reset),
    .io_push    (InstFifoVec_1_io_push),
    .io_inst_In (InstFifoVec_1_io_inst_In),
    .io_inst_Q  (InstFifoVec_1_io_inst_Q)
  );
  wire        InstFifoVec_2_io_push;
  InstFifo InstFifoVec_2 (
    .clock      (clock),
    .reset      (reset),
    .io_push    (InstFifoVec_2_io_push),
    .io_inst_In (InstFifoVec_2_io_inst_In),
    .io_inst_Q  (InstFifoVec_2_io_inst_Q)
  );
  wire        InstFifoVec_3_io_push;
  InstFifo InstFifoVec_3 (
    .clock      (clock),
    .reset      (reset),
    .io_push    (InstFifoVec_3_io_push),
    .io_inst_In (InstFifoVec_3_io_inst_In),
    .io_inst_Q  (InstFifoVec_3_io_inst_Q)
  );
  reg  [1:0]  bankWritePtr_Q;
  wire [3:0]  fetchValidVecShifter_io_in;
  wire [1:0]  fetchValidVecShifter_io_shiftNum = bankWritePtr_Q;
  leftCircularShift fetchValidVecShifter (
    .clock       (clock),
    .reset       (reset),
    .io_in       (fetchValidVecShifter_io_in),
    .io_shiftNum (fetchValidVecShifter_io_shiftNum),
    .io_out      (fetchValidVecShifter_io_out)
  );
  assign fetchValidVecShifter_io_in =
    {io_fetchValidVec_3_0,
     io_fetchValidVec_2_0,
     io_fetchValidVec_1_0,
     io_fetchValidVec_0_0};
  assign InstFifoVec_0_io_push = fetchValidVecShifter_io_out[0];
  assign InstFifoVec_1_io_push = fetchValidVecShifter_io_out[1];
  assign InstFifoVec_2_io_push = fetchValidVecShifter_io_out[2];
  assign InstFifoVec_3_io_push = fetchValidVecShifter_io_out[3];
  always @(posedge clock or posedge reset) begin
    if (reset)
      bankWritePtr_Q <= 2'h0;
    else
      bankWritePtr_Q <= bankWritePtr_Q;
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset)
        bankWritePtr_Q = 2'h0;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
endmodule

