// Generated by CIRCT firtool-1.128.0
module InstQueue(
  input         clock,
  input         reset,
  input         io_fetchValidVec_0,
  output        io_enqueueAllowIn,
  input  [31:0] io_fetchInstVec_0
);

  wire [31:0] InstFifoVec_0_io_dout;
  wire        io_fetchValidVec_0_0 = io_fetchValidVec_0;
  wire [31:0] io_fetchInstVec_0_0 = io_fetchInstVec_0;
  wire        InstFifoVec_0_io_pop = 1'h0;
  wire        InstFifoVec_0_io_push = io_fetchValidVec_0_0;
  wire [31:0] InstFifoVec_0_io_din = io_fetchInstVec_0_0;
  reg  [3:0]  queueSize_Q;
  wire [3:0]  enqueueNum;
  wire [4:0]  _GEN = 5'({1'h0, queueSize_Q} + {1'h0, enqueueNum});
  wire        io_enqueueAllowIn_0 = _GEN[3:0] <= 4'h8;
  wire        _GEN_0 = (|io_fetchValidVec_0_0) & io_enqueueAllowIn_0;
  assign enqueueNum = {3'h0, io_fetchValidVec_0_0};
  wire [3:0]  dequeueNum = 4'h0;
  wire [4:0]  _GEN_1 = 5'({1'h0, queueSize_Q} + {1'h0, _GEN_0 ? enqueueNum : 4'h0});
  wire [4:0]  _GEN_2 = 5'({1'h0, _GEN_1[3:0]} - {1'h0, dequeueNum});
  wire [3:0]  queueSize_In = _GEN_2[3:0];
  BasicFifo InstFifoVec_0 (
    .clock   (clock),
    .reset   (reset),
    .io_push (InstFifoVec_0_io_push),
    .io_pop  (InstFifoVec_0_io_pop),
    .io_din  (InstFifoVec_0_io_din),
    .io_dout (InstFifoVec_0_io_dout)
  );
  always @(posedge clock or posedge reset) begin
    if (reset)
      queueSize_Q <= 4'h0;
    else if (_GEN_0)
      queueSize_Q <= queueSize_In;
    else begin
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset)
        queueSize_Q = 4'h0;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_enqueueAllowIn = io_enqueueAllowIn_0;
endmodule

