// Generated by CIRCT firtool-1.128.0
module InstFifoEntry(
  input         clock,
  input         reset,
  input         io_wen,
  input  [31:0] io_inst_In,
  output [31:0] io_inst_Q
);

  wire        io_wen_0 = io_wen;
  wire [31:0] io_inst_In_0 = io_inst_In;
  reg  [31:0] instReg;
  wire [31:0] io_inst_Q_0 = instReg;
  always @(posedge clock) begin
    if (io_wen_0)
      instReg <= io_inst_In_0;
    else begin
    end
  end // always @(posedge)
  assign io_inst_Q = io_inst_Q_0;
endmodule

