// Generated by CIRCT firtool-1.128.0
module InstFifo(
  input         clock,
  input         reset,
  input         io_push,
  input  [31:0] io_inst_In,
  output [31:0] io_inst_Q
);

  wire [31:0] entryArray_7_io_inst_Q;
  wire [31:0] entryArray_6_io_inst_Q;
  wire [31:0] entryArray_5_io_inst_Q;
  wire [31:0] entryArray_4_io_inst_Q;
  wire [31:0] entryArray_3_io_inst_Q;
  wire [31:0] entryArray_2_io_inst_Q;
  wire [31:0] entryArray_1_io_inst_Q;
  wire        io_push_0 = io_push;
  wire [31:0] io_inst_In_0 = io_inst_In;
  wire [31:0] entryArray_0_io_inst_In = io_inst_In_0;
  wire [31:0] entryArray_0_io_inst_Q;
  wire [31:0] entryArray_1_io_inst_In = io_inst_In_0;
  wire [31:0] entryArray_2_io_inst_In = io_inst_In_0;
  wire [31:0] entryArray_3_io_inst_In = io_inst_In_0;
  wire [31:0] entryArray_4_io_inst_In = io_inst_In_0;
  wire [31:0] entryArray_5_io_inst_In = io_inst_In_0;
  wire [31:0] entryArray_6_io_inst_In = io_inst_In_0;
  wire [31:0] entryArray_7_io_inst_In = io_inst_In_0;
  wire        entryArray_0_io_wen;
  InstFifoEntry entryArray_0 (
    .clock      (clock),
    .reset      (reset),
    .io_wen     (entryArray_0_io_wen),
    .io_inst_In (entryArray_0_io_inst_In),
    .io_inst_Q  (entryArray_0_io_inst_Q)
  );
  wire [31:0] io_inst_Q_0 = entryArray_0_io_inst_Q;
  wire        entryArray_1_io_wen;
  InstFifoEntry entryArray_1 (
    .clock      (clock),
    .reset      (reset),
    .io_wen     (entryArray_1_io_wen),
    .io_inst_In (entryArray_1_io_inst_In),
    .io_inst_Q  (entryArray_1_io_inst_Q)
  );
  wire        entryArray_2_io_wen;
  InstFifoEntry entryArray_2 (
    .clock      (clock),
    .reset      (reset),
    .io_wen     (entryArray_2_io_wen),
    .io_inst_In (entryArray_2_io_inst_In),
    .io_inst_Q  (entryArray_2_io_inst_Q)
  );
  wire        entryArray_3_io_wen;
  InstFifoEntry entryArray_3 (
    .clock      (clock),
    .reset      (reset),
    .io_wen     (entryArray_3_io_wen),
    .io_inst_In (entryArray_3_io_inst_In),
    .io_inst_Q  (entryArray_3_io_inst_Q)
  );
  wire        entryArray_4_io_wen;
  InstFifoEntry entryArray_4 (
    .clock      (clock),
    .reset      (reset),
    .io_wen     (entryArray_4_io_wen),
    .io_inst_In (entryArray_4_io_inst_In),
    .io_inst_Q  (entryArray_4_io_inst_Q)
  );
  wire        entryArray_5_io_wen;
  InstFifoEntry entryArray_5 (
    .clock      (clock),
    .reset      (reset),
    .io_wen     (entryArray_5_io_wen),
    .io_inst_In (entryArray_5_io_inst_In),
    .io_inst_Q  (entryArray_5_io_inst_Q)
  );
  wire        entryArray_6_io_wen;
  InstFifoEntry entryArray_6 (
    .clock      (clock),
    .reset      (reset),
    .io_wen     (entryArray_6_io_wen),
    .io_inst_In (entryArray_6_io_inst_In),
    .io_inst_Q  (entryArray_6_io_inst_Q)
  );
  wire        entryArray_7_io_wen;
  InstFifoEntry entryArray_7 (
    .clock      (clock),
    .reset      (reset),
    .io_wen     (entryArray_7_io_wen),
    .io_inst_In (entryArray_7_io_inst_In),
    .io_inst_Q  (entryArray_7_io_inst_Q)
  );
  reg  [7:0]  writePtrDcd_Q;
  wire [7:0]  writePtrDcd_In = {writePtrDcd_Q[6:0], writePtrDcd_Q[7]};
  assign entryArray_0_io_wen = io_push_0 & writePtrDcd_Q[0];
  assign entryArray_1_io_wen = io_push_0 & writePtrDcd_Q[1];
  assign entryArray_2_io_wen = io_push_0 & writePtrDcd_Q[2];
  assign entryArray_3_io_wen = io_push_0 & writePtrDcd_Q[3];
  assign entryArray_4_io_wen = io_push_0 & writePtrDcd_Q[4];
  assign entryArray_5_io_wen = io_push_0 & writePtrDcd_Q[5];
  assign entryArray_6_io_wen = io_push_0 & writePtrDcd_Q[6];
  assign entryArray_7_io_wen = io_push_0 & writePtrDcd_Q[7];
  always @(posedge clock or posedge reset) begin
    if (reset)
      writePtrDcd_Q <= 8'h0;
    else if (io_push_0)
      writePtrDcd_Q <= writePtrDcd_In;
    else begin
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset)
        writePtrDcd_Q = 8'h0;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_inst_Q = io_inst_Q_0;
endmodule

