// Generated by CIRCT firtool-1.128.0
module leftCircularShift(
  input        clock,
  input        reset,
  input  [3:0] io_in,
  input  [1:0] io_shiftNum,
  output [3:0] io_out
);

  wire [3:0] io_in_0 = io_in;
  wire [1:0] io_shiftNum_0 = io_shiftNum;
  wire [3:0] shiftCandidates_0 = io_in_0;
  wire [3:0] shiftCandidates_1 = {io_in_0[2:0], io_in_0[3]};
  wire [3:0] shiftCandidates_2 = {io_in_0[1:0], io_in_0[3:2]};
  wire [3:0] shiftCandidates_3 = {io_in_0[0], io_in_0[3:1]};
  wire [3:0] _GEN = 4'h1 << io_shiftNum_0;
  wire [3:0] io_out_0 =
    (_GEN[0] ? shiftCandidates_0 : 4'h0) | (_GEN[1] ? shiftCandidates_1 : 4'h0)
    | (_GEN[2] ? shiftCandidates_2 : 4'h0) | (_GEN[3] ? shiftCandidates_3 : 4'h0);
  assign io_out = io_out_0;
endmodule

