// Generated by CIRCT firtool-1.128.0
module XcoreTop(
  input          clock,
  input          reset,
  output         io_axiChannel_arChannel_arValid,
  input          io_axiChannel_arChannel_arReady,
  output [31:0]  io_axiChannel_arChannel_arAddr,
  input          io_axiChannel_rChannel_rValid,
  output         io_axiChannel_rChannel_rReady,
  input  [127:0] io_axiChannel_rChannel_rData
);

  wire [4:0]   decoderVec_0_io_uop_ldst;
  wire [4:0]   decoderVec_0_io_uop_lsrc2;
  wire [4:0]   decoderVec_0_io_uop_lsrc1;
  wire [31:0]  ifuTop_io_instVec_0;
  wire         ifuTop_io_instValidVec_0;
  wire         io_axiChannel_arChannel_arReady_0 = io_axiChannel_arChannel_arReady;
  wire         io_axiChannel_rChannel_rValid_0 = io_axiChannel_rChannel_rValid;
  wire [127:0] io_axiChannel_rChannel_rData_0 = io_axiChannel_rChannel_rData;
  wire         ifuTop_io_ifuARChannel_arValid;
  wire         ifuTop_io_ifuARChannel_arReady = io_axiChannel_arChannel_arReady_0;
  wire [31:0]  ifuTop_io_ifuARChannel_arAddr;
  wire         ifuTop_io_ifuRChannel_rValid = io_axiChannel_rChannel_rValid_0;
  wire         ifuTop_io_ifuRChannel_rReady;
  wire [127:0] ifuTop_io_ifuRChannel_rData = io_axiChannel_rChannel_rData_0;
  IfuTop ifuTop (
    .clock                   (clock),
    .reset                   (reset),
    .io_ifuARChannel_arValid (ifuTop_io_ifuARChannel_arValid),
    .io_ifuARChannel_arReady (ifuTop_io_ifuARChannel_arReady),
    .io_ifuARChannel_arAddr  (ifuTop_io_ifuARChannel_arAddr),
    .io_ifuRChannel_rValid   (ifuTop_io_ifuRChannel_rValid),
    .io_ifuRChannel_rReady   (ifuTop_io_ifuRChannel_rReady),
    .io_ifuRChannel_rData    (ifuTop_io_ifuRChannel_rData),
    .io_instValidVec_0       (ifuTop_io_instValidVec_0),
    .io_instVec_0            (ifuTop_io_instVec_0)
  );
  wire         io_axiChannel_arChannel_arValid_0 = ifuTop_io_ifuARChannel_arValid;
  wire [31:0]  io_axiChannel_arChannel_arAddr_0 = ifuTop_io_ifuARChannel_arAddr;
  wire         io_axiChannel_rChannel_rReady_0 = ifuTop_io_ifuRChannel_rReady;
  wire [31:0]  decoderVec_0_io_inst = ifuTop_io_instVec_0;
  Decoder decoderVec_0 (
    .clock        (clock),
    .reset        (reset),
    .io_inst      (decoderVec_0_io_inst),
    .io_uop_lsrc1 (decoderVec_0_io_uop_lsrc1),
    .io_uop_lsrc2 (decoderVec_0_io_uop_lsrc2),
    .io_uop_ldst  (decoderVec_0_io_uop_ldst)
  );
  assign io_axiChannel_arChannel_arValid = io_axiChannel_arChannel_arValid_0;
  assign io_axiChannel_arChannel_arAddr = io_axiChannel_arChannel_arAddr_0;
  assign io_axiChannel_rChannel_rReady = io_axiChannel_rChannel_rReady_0;
endmodule

